# Generated by Django 3.0 on 2019-12-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20191221_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Hakkımda'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_area',
            field=models.ManyToManyField(blank=True, help_text='Çalışma Alanınızı Seçiniz', related_name='alan', to='auths.working_area', verbose_name='Çalışma Alanı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_position',
            field=models.ManyToManyField(blank=True, help_text='Çalışma Pozisyonunuzu Seçiniz', related_name='pozisyon', to='auths.working_position', verbose_name='Çalışma Pozisyonu'),
        ),
    ]
