# Generated by Django 3.0 on 2019-12-24 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0045_auto_20191222_1917'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auths', '0003_auto_20191221_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_work_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.CharField(max_length=25, null=True, verbose_name='İlk İşe Giriş Tarihiniz')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduated_site.company', verbose_name='Çalıştığınız Firma')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name_plural': 'Çalışılan Firmalar',
            },
        ),
    ]
