# Generated by Django 3.0 on 2019-12-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_auto_20191225_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='working_area',
            field=models.CharField(blank=True, choices=[('None', 'Çalışma Alanınızı Seçiniz'), ('YAPAY ZEKA', 'YAPAY ZEKA'), ('SES İŞLEME', 'SES İŞLEME'), ('GÖRÜNTÜ İŞLEME', 'GÖRÜNTÜ İŞLEME'), ('ADLİ BİLİŞİM', 'ADLİ BİLİŞİM')], max_length=25, null=True, verbose_name='Çalışma Alanı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_position',
            field=models.CharField(blank=True, choices=[('None', 'Çalışma Pozisyonunuzu Seçiniz'), ('STAJYER', 'STAJYER'), ('MENAJER', 'MENAJER'), ('PROGRAMCI', 'PROGRAMCI'), ('TEKNİKER', 'TEKNİKER')], max_length=25, null=True, verbose_name='Çalışma Pozisyonu'),
        ),
    ]
