# Generated by Django 3.0 on 2019-12-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_user_message_box'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_message_box',
            options={'verbose_name_plural': 'Mesajlar'},
        ),
    ]
