# Generated by Django 3.0 on 2019-12-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0009_auto_20191225_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_message_box',
            name='message_title',
            field=models.CharField(max_length=25, null=True, verbose_name='Mesaj Başlığı'),
        ),
    ]
