# Generated by Django 3.0 on 2019-12-25 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0047_delete_user_job_adv_post'),
        ('auths', '0010_user_message_box_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='graduated_site.company', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_day',
            field=models.DateField(blank=True, null=True, verbose_name='Firmadaki İlk Gününüz'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='graduated_day',
            field=models.DateField(blank=True, null=True, verbose_name='Mezun Olduğunuz Gün'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_day',
            field=models.DateField(blank=True, null=True, verbose_name='Firmadan Çıkış Gününüz'),
        ),
    ]
