# Generated by Django 3.0 on 2019-12-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0011_auto_20191225_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='graduated_day',
            new_name='graduated_date',
        ),
    ]
