# Generated by Django 3.0 on 2020-03-05 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0050_auto_20191225_2344'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auths', '0012_auto_20191225_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_message_box',
            options={'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='user_work_company',
            options={'verbose_name_plural': 'Work Company'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='user_message_box',
            name='message',
            field=models.CharField(max_length=500, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='user_message_box',
            name='message_title',
            field=models.CharField(max_length=25, null=True, verbose_name='Message Title'),
        ),
        migrations.AlterField(
            model_name='user_message_box',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_user', to=settings.AUTH_USER_MODEL, verbose_name='User Send a Message'),
        ),
        migrations.AlterField(
            model_name='user_message_box',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sending_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user_work_company',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduated_site.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='user_work_company',
            name='first_day',
            field=models.CharField(max_length=25, null=True, verbose_name='Your First Day In Company'),
        ),
        migrations.AlterField(
            model_name='user_work_company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='certificate',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='graduated_site.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_day',
            field=models.DateField(blank=True, null=True, verbose_name='Your First Day In Company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foreign_language',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Foreign Languages'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='graduated_date',
            field=models.DateField(blank=True, null=True, verbose_name='Graduated Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_day',
            field=models.DateField(blank=True, null=True, verbose_name='Your Last Day In Company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_area',
            field=models.CharField(blank=True, choices=[('ARTIFICAL INTELLIGENCE', 'ARTIFICAL INTELLIGENCE'), ('SOUND PROCESSING', 'SOUND PROCESSING'), ('IMAGE PROCESSING', 'IMAGE PROCESSING'), ('COMPUTER FORENSICS', 'COMPUTER FORENSICS')], max_length=25, null=True, verbose_name='Working Area'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_position',
            field=models.CharField(blank=True, choices=[('INTERN', 'INTERN'), ('MANAGER', 'MANAGER'), ('PROGRAMMER', 'PROGRAMMER'), ('TECHNICIAN', 'TECHNICIAN')], max_length=25, null=True, verbose_name='Working Position'),
        ),
    ]
