# Generated by Django 3.0 on 2020-03-07 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auths', '0013_auto_20200305_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_message_box',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_user', to=settings.AUTH_USER_MODEL, verbose_name='Message To User'),
        ),
    ]
