# Generated by Django 3.0 on 2019-12-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_internship_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='İlan Başlığını Giriniz')),
                ('content', models.CharField(max_length=1000, null=True, verbose_name='İlan İçeriğini Giriniz')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('company_choice', models.CharField(max_length=50, null=True, verbose_name='Şirket Seçiniz')),
            ],
            options={
                'verbose_name_plural': 'userInthernshipPost',
                'ordering': ['created_date'],
            },
        ),
    ]
