# Generated by Django 3.0 on 2019-12-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_job_adv_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='İlan Başlığını Giriniz')),
            ],
        ),
        migrations.AddField(
            model_name='user_internship_post',
            name='deadline',
            field=models.DateField(max_length=15, null=True, verbose_name='Son Başvuru Tarihi'),
        ),
    ]
