# Generated by Django 3.0 on 2019-12-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0003_auto_20191217_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='working_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30, verbose_name='Çalışma Alanı')),
            ],
            options={
                'verbose_name_plural': 'Çalışma Alanları',
            },
        ),
    ]
