# Generated by Django 3.0 on 2019-12-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0004_working_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_internship_post',
            name='working_area',
            field=models.ManyToManyField(null=True, to='graduated_site.working_area'),
        ),
    ]
