# Generated by Django 3.0 on 2019-12-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0006_auto_20191218_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_internship_post',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='user_internship_post',
            name='working_area',
            field=models.ManyToManyField(null=True, related_name='alan', to='graduated_site.working_area', verbose_name='Çalışma Alanları'),
        ),
    ]
