# Generated by Django 3.0 on 2019-12-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0011_auto_20191218_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='image',
            field=models.ImageField(blank=True, help_text='Firma veya ilan göreseli ekleyebilirsiniz', null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
