# Generated by Django 3.0 on 2019-12-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0012_auto_20191218_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='title',
            field=models.CharField(help_text='İlan Başlığını Giriniz', max_length=50, null=True, verbose_name='Başlık'),
        ),
    ]
