# Generated by Django 3.0 on 2019-12-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0014_auto_20191218_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='image',
            field=models.ImageField(blank=True, help_text='Firma veya ilan görseli ekleyebilirsiniz.', null=True, upload_to='', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='user_internship_post',
            name='title',
            field=models.CharField(help_text='İlan Başlığını Giriniz.', max_length=50, null=True, verbose_name='Başlık'),
        ),
    ]
