# Generated by Django 3.0 on 2019-12-18 13:34

from django.db import migrations, models
import graduated_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0015_auto_20191218_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_internship_post',
            name='unique_id',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_internship_post',
            name='content',
            field=models.CharField(help_text='İlan içeriğini giriniz.', max_length=1000, null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='user_internship_post',
            name='image',
            field=models.ImageField(blank=True, help_text='Firma veya ilan görseli ekleyebilirsiniz.', null=True, upload_to=graduated_site.models.upload_to, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='user_internship_post',
            name='title',
            field=models.CharField(help_text='İlan başlığını giriniz.', max_length=50, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='user_internship_post',
            name='working_area',
            field=models.ManyToManyField(help_text='İstenilen çalışma alanlarını seçiniz.(Birden fazla seçilebilir.)', related_name='alan', to='graduated_site.working_area', verbose_name='Çalışma Alanları'),
        ),
    ]
