# Generated by Django 3.0 on 2019-12-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0016_auto_20191218_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
