# Generated by Django 3.0 on 2019-12-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0017_auto_20191218_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_internship_post',
            name='adv_type',
            field=models.CharField(choices=[(None, 'Lütfen İlan Tipini Seçiniz'), ('0', 'STAJ'), ('1', 'İŞ')], max_length=10, null=True),
        ),
    ]
