# Generated by Django 3.0 on 2019-12-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0023_auto_20191218_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='adv_type',
            field=models.CharField(choices=[(None, 'Lütfen İlan Tipini Seçiniz'), ('staj', 'STAJ1'), ('is', 'İŞ')], max_length=10, null=True),
        ),
    ]
