# Generated by Django 3.0 on 2019-12-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0026_auto_20191218_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='adv_type',
            field=models.CharField(choices=[(None, 'Lütfen İlan Tipini Seçiniz'), ('0', 'STAJ'), ('1', 'İŞ')], max_length=10, null=True),
        ),
    ]
