# Generated by Django 3.0 on 2019-12-18 20:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0027_auto_20191218_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='İlan içeriğini giriniz.', max_length=2000, null=True, verbose_name='İçerik'),
        ),
    ]
