# Generated by Django 3.0 on 2019-12-18 21:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0029_auto_20191218_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=2000, null=True, verbose_name='İcerik'),
        ),
    ]
