# Generated by Django 3.0 on 2019-12-18 21:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0030_auto_20191218_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='İlan içeriğini giriniz.', max_length=1000, null=True, verbose_name='İçerik'),
        ),
    ]
