# Generated by Django 3.0 on 2019-12-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0032_auto_20191218_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim')),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyisim')),
                ('email', models.EmailField(help_text='Bu Alan Zorunludur.', max_length=254, null=True, verbose_name='E-mail')),
                ('content', models.CharField(max_length=500, null=True, verbose_name='Yorum')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='graduated_site.user_internship_post')),
            ],
            options={
                'verbose_name_plural': 'Yorumlar',
            },
        ),
    ]
