# Generated by Django 3.0 on 2019-12-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0035_auto_20191219_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='Telefon Numarası')),
                ('adress', models.CharField(max_length=200, null=True, verbose_name='Adres')),
                ('company_name', models.CharField(max_length=25, null=True, verbose_name='Şirket Adı')),
                ('company_type', models.CharField(max_length=25, null=True, verbose_name='Şirket Türü')),
                ('company_sector', models.ManyToManyField(help_text='Şirketin çalışma alanlarını seçiniz.(Birden fazla seçilebilir.)', related_name='sektör', to='graduated_site.working_area', verbose_name='Şirket Sektörü')),
            ],
        ),
    ]
