# Generated by Django 3.0 on 2019-12-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0036_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Şirketler'},
        ),
    ]
