# Generated by Django 3.0 on 2019-12-21 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graduated_site', '0038_user_internship_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
