# Generated by Django 3.0 on 2019-12-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0042_auto_20191222_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_internship_post',
            name='company_choice',
        ),
    ]
