# Generated by Django 3.0 on 2019-12-22 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graduated_site', '0043_remove_user_internship_post_company_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_internship_post',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduated_site.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='user_internship_post',
            name='adv_type',
            field=models.CharField(choices=[(None, 'Lütfen İlan Tipini Seçiniz'), ('0', 'STAJ'), ('1', 'İŞ')], max_length=10, null=True, verbose_name='İlan Tipini Seçiniz'),
        ),
        migrations.AlterField(
            model_name='user_internship_post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
