# Generated by Django 3.0 on 2019-12-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0044_auto_20191222_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduated_site.company', verbose_name='Firma Seçiniz'),
        ),
    ]
