# Generated by Django 3.0 on 2019-12-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0046_auto_20191225_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_job_adv_post',
        ),
    ]
