# Generated by Django 3.0 on 2019-12-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0047_delete_user_job_adv_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='working_area',
            field=models.ManyToManyField(blank=True, help_text='İstenilen çalışma alanlarını seçiniz.(Birden fazla seçilebilir.)', related_name='alan', to='graduated_site.working_area', verbose_name='Çalışma Alanları'),
        ),
    ]
