# Generated by Django 3.0 on 2019-12-25 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graduated_site', '0048_auto_20191225_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_internship_post',
            options={'ordering': ['deadline'], 'verbose_name_plural': 'İlanlar'},
        ),
        migrations.CreateModel(
            name='survey_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=50, null=True, verbose_name='Ad Soyad *')),
                ('graduated_year', models.CharField(max_length=4, null=True, verbose_name='Mezuniyet Yılı *')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='E-posta *')),
                ('phone_number', models.CharField(max_length=12, null=True, verbose_name='Telefon *')),
                ('graduated_program', models.CharField(blank=True, max_length=25, null=True, verbose_name='Mezun Olduğunuz Program')),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adres')),
                ('social_profile', models.CharField(blank=True, max_length=50, null=True, verbose_name='En Yoğun Kullandığınız Sosyal Medya Profil Sayfanız')),
                ('graduated_state', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mezuniyet Durumunuz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name_plural': 'Anketler',
            },
        ),
    ]
