# Generated by Django 3.0 on 2020-03-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduated_site', '0051_auto_20200307_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_internship_post',
            name='period_internship',
            field=models.CharField(blank=True, choices=[(None, 'Please select internship period'), ('YAZ', 'YAZ'), ('BAHAR', 'BAHAR'), ('KIŞ', 'KIŞ'), ('GÜZ', 'GÜZ')], max_length=25, null=True, verbose_name='Internship Period'),
        ),
        migrations.AlterField(
            model_name='user_internship_post',
            name='time_internship',
            field=models.CharField(blank=True, choices=[(None, 'Please select internship duration'), ('30 GÜN', '30 GÜN'), ('60 GÜN', '60 GÜN')], max_length=25, null=True, verbose_name='Internship Duration'),
        ),
    ]
